Join-Title-Message: "&e&lThis is a Title {player}" # {player} for it to display the players name.
Join-Sub-Title-Message: "&3&lThis is a Sub Title" # {player} for it to display the players name.

Header: "&eWelcome to YetiAnarchy!!" # this is the top of the tab list {player} also works here and the footer.
Footer: "&eVersion: {version}" # {version} allows you to show the version of the server without typing 1.20.2 etc....